### ISSUE TITLE
Direct link to job statistics

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-activejobs#45] opened 2016-05-09 19:53 UTC
Provide a direct link that can be shared between users that shows them the view for a single job.

**Comment by nickjer** [comment] 2018-03-15 15:38
This issue was brought up again by Shameema after a workshop she recently gave.

**Comment by nickjer** [comment] 2018-03-15 15:45
Similar to a show view that a Rails resource provides. Basically it is a single page that shows the full details of a job (similar to what we show when you expand the row in the table) but in a single HTML page.

**Comment by nickjer** [comment] 2018-03-15 15:46
Adding @brianmcmichael and @ericfranz as participants.

**Comment by ericfranz** [comment] 2018-08-02 22:58
Duplicate of #160

**Closed by ericfranz** 2018-08-02 22:58 UTC
Labels: duplicate, enhancement
